export const NAVIGATION_LINKS = [
  {
    label: "Home",
    to: "/",
    icon: "/nav-icons/home_outline.svg",
    iconActive: "/nav-icons/home_fill.svg",
    isEnabled: true,
  },
  {
    label: "Explore",
    to: "#",
    icon: "/nav-icons/explore_outline.svg",
    iconActive: "/nav-icons/explore_fill.svg",
    isEnabled: false,
  },
  {
    label: "Notifications",
    to: "#",
    icon: "/nav-icons/notification_outline.svg",
    iconActive: "/nav-icons/notification_fill.svg",
    isEnabled: false,
  },
  {
    label: "Messages",
    to: "#",
    icon: "/nav-icons/message_outline.svg",
    iconActive: "/nav-icons/message_fill.svg",
    isEnabled: false,
  },
  {
    label: "Bookmarks",
    to: "#",
    icon: "/nav-icons/bookmark_outline.svg",
    iconActive: "/nav-icons/bookmark_fill.svg",
    isEnabled: false,
  },
  {
    label: "Lists",
    to: "#",
    icon: "/nav-icons/list_outline.svg",
    iconActive: "/nav-icons/list_fill.svg",
    isEnabled: false,
  },
  {
    label: "Profile",
    to: "/profile/1",
    icon: "/nav-icons/profile_outline.svg",
    iconActive: "/nav-icons/profile_fill.svg",
    isEnabled: true,
  },
  {
    label: "More",
    to: "#",
    icon: "/nav-icons/more.svg",
    iconActive: "/nav-icons/more.svg",
    isEnabled: false,
  },
];
